services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: routecalc-postgres
    environment:
      POSTGRES_DB: rotas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rotas_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - routecalc-network

  # PgAdmin para gerenciamento do banco (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: routecalc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@routecalc.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - routecalc-network
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local

networks:
  routecalc-network:
    driver: bridge
