services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: routecalc-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rotas_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-rotas_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - routecalc-network

  # Backend FastAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: routecalc-backend
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-rotas_db}
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/__pycache__
    working_dir: /app
    networks:
      - routecalc-network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: ./route-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5001/api/v1
    container_name: routecalc-frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api/v1
    depends_on:
      - backend
    networks:
      - routecalc-network
    restart: unless-stopped

  # Frontend para desenvolvimento (opcional)
  frontend-dev:
    build:
      context: ./route-frontend
      dockerfile: Dockerfile.dev
    container_name: routecalc-frontend-dev
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api/v1
    depends_on:
      - backend
    volumes:
      - ./route-frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - routecalc-network
    profiles:
      - dev

  # PgAdmin para gerenciamento do banco (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: routecalc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@routecalc.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - routecalc-network
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local

networks:
  routecalc-network:
    driver: bridge