services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: routecalc-postgres
    environment:
      POSTGRES_DB: rotas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rotas_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - routecalc-network

volumes:
  postgres_data:
    driver: local

networks:
  routecalc-network:
    driver: bridge
